### ISSUE TITLE
problem running code

### ISSUE THREAD

**Issue by sycdlcrain** [shaohua0116/demo2program#2]
Hi, I liked your paper and was interested in trying out your code. 
i'm having a problem running the data synthesis:
python trainer.py --model synthesis_baseline --dataset_path /my_path/demo2program/datasets/karel_dataset/ --dataset_type karel

first error was a typo on line 249 of trainer.py "defiault=" 

second error is harder to diagnose:
demo2program$ python trainer.py --model synthesis_baseline --dataset_path /home/h/demo2program/datasets/karel_dataset/ --dataset_type karel
[2018-09-12 15:18:17,938] Reading /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5 ...
[2018-09-12 15:18:17,939] Reading Done: /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5
[2018-09-12 15:18:17,939] Reading /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5 ...
[2018-09-12 15:18:17,940] Reading Done: /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5
[2018-09-12 15:18:17,940] Reading /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5 ...
[2018-09-12 15:18:17,941] Reading Done: /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/data.hdf5
[2018-09-12 15:18:17,944] Train Dir: ./train_dir/karel-_home_disele_Documents_PROJ_program_synth_demo2program_datasets_karel_dataset_-synthesis_baseline-default-bs_32_lr_0.001_lstm_cell_512_k_10-20180912-151817
[2018-09-12 15:18:17,944] input_ops [inputs]: Using 25000 IDs from dataset
[2018-09-12 15:18:18,036] input_ops [inputs]: Using 5000 IDs from dataset
[2018-09-12 15:18:18,078] Using Model class: <class 'models.baselines.model_synthesis.Model'>
[2018-09-12 15:18:18,181] Demo_Encoder
[2018-09-12 15:18:18,183] Demo_Encoder/State_Encoder
[2018-09-12 15:18:18,229] conv1 Tensor("Demo_Encoder/State_Encoder/conv1/bn_act/BatchNorm/batchnorm/add_1:0", shape=(640, 4, 4, 16), dtype=float32)
[2018-09-12 15:18:18,274] conv2 Tensor("Demo_Encoder/State_Encoder/conv2/bn_act/BatchNorm/batchnorm/add_1:0", shape=(640, 2, 2, 32), dtype=float32)
[2018-09-12 15:18:18,320] conv3 Tensor("Demo_Encoder/State_Encoder/conv3/bn_act/BatchNorm/batchnorm/add_1:0", shape=(640, 1, 1, 48), dtype=float32)
[2018-09-12 15:18:18,425] Tensor("Demo_Encoder/rnn/transpose:0", shape=(32, 20, 512), dtype=float32)
[2018-09-12 15:18:20,184] Program_Decoder/Token_Embedding
Successfully loaded the model.
[2018-09-12 15:18:21,059] ********* var ********** 
---------
Variables: name (type shape) [size]
---------
Demo_Encoder/State_Encoder/conv1/Conv/weights:0 (float32_ref 3x3x16x16) [2304, bytes: 9216]
Demo_Encoder/State_Encoder/conv1/Conv/biases:0 (float32_ref 16) [16, bytes: 64]
Demo_Encoder/State_Encoder/conv1/bn_act/BatchNorm/beta:0 (float32_ref 16) [16, bytes: 64]
Demo_Encoder/State_Encoder/conv1/bn_act/BatchNorm/gamma:0 (float32_ref 16) [16, bytes: 64]
Demo_Encoder/State_Encoder/conv2/Conv/weights:0 (float32_ref 3x3x16x32) [4608, bytes: 18432]
Demo_Encoder/State_Encoder/conv2/Conv/biases:0 (float32_ref 32) [32, bytes: 128]
Demo_Encoder/State_Encoder/conv2/bn_act/BatchNorm/beta:0 (float32_ref 32) [32, bytes: 128]
Demo_Encoder/State_Encoder/conv2/bn_act/BatchNorm/gamma:0 (float32_ref 32) [32, bytes: 128]
Demo_Encoder/State_Encoder/conv3/Conv/weights:0 (float32_ref 3x3x32x48) [13824, bytes: 55296]
Demo_Encoder/State_Encoder/conv3/Conv/biases:0 (float32_ref 48) [48, bytes: 192]
Demo_Encoder/State_Encoder/conv3/bn_act/BatchNorm/beta:0 (float32_ref 48) [48, bytes: 192]
Demo_Encoder/State_Encoder/conv3/bn_act/BatchNorm/gamma:0 (float32_ref 48) [48, bytes: 192]
Demo_Encoder/rnn/basic_lstm_cell/kernel:0 (float32_ref 560x2048) [1146880, bytes: 4587520]
Demo_Encoder/rnn/basic_lstm_cell/bias:0 (float32_ref 2048) [2048, bytes: 8192]
Program_Decoder/Token_Embedding/embedding_map:0 (float32_ref 51x512) [26112, bytes: 104448]
Program_Decoder/dynamic_decoder/basic_lstm_cell/kernel:0 (float32_ref 1024x2048) [2097152, bytes: 8388608]
Program_Decoder/dynamic_decoder/basic_lstm_cell/bias:0 (float32_ref 2048) [2048, bytes: 8192]
Program_Decoder/dynamic_decoder/output_projection/kernel:0 (float32_ref 512x50) [25600, bytes: 102400]
Total size of variables: 3320864
Total bytes of variables: 13283456
2018-09-12 15:18:33.107136: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-12 15:18:33.107163: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-12 15:18:33.107168: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-09-12 15:18:33.107172: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-12 15:18:33.107176: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[2018-09-12 15:18:49,161] dataset: /home/disele/Documents/PROJ_program_synth/demo2program/datasets/karel_dataset/, learning_rate: 0.001000
[2018-09-12 15:18:49,162] Training Starts!
{'a_h': <tf.Tensor 'shuffle_batch:0' shape=(32, 10, 20, 6) dtype=float32>,
 'a_h_tokens': <tf.Tensor 'shuffle_batch:1' shape=(32, 10, 20) dtype=int32>,
 'demo_len': <tf.Tensor 'shuffle_batch:2' shape=(32, 10) dtype=float32>,
 'id': <tf.Tensor 'shuffle_batch:3' shape=(32,) dtype=string>,
 'per': <tf.Tensor 'shuffle_batch:4' shape=(32, 10, 20, 5) dtype=float32>,
 'program': <tf.Tensor 'shuffle_batch:5' shape=(32, 50, 43) dtype=float32>,
 'program_len': <tf.Tensor 'shuffle_batch:6' shape=(32, 1) dtype=float32>,
 'program_tokens': <tf.Tensor 'shuffle_batch:7' shape=(32, 43) dtype=int32>,
 's_h': <tf.Tensor 'shuffle_batch:8' shape=(32, 10, 20, 8, 8, 16) dtype=float32>,
 'test_a_h': <tf.Tensor 'shuffle_batch:9' shape=(32, 5, 20, 6) dtype=float32>,
 'test_a_h_tokens': <tf.Tensor 'shuffle_batch:10' shape=(32, 5, 20) dtype=int32>,
 'test_demo_len': <tf.Tensor 'shuffle_batch:11' shape=(32, 5) dtype=float32>,
 'test_per': <tf.Tensor 'shuffle_batch:12' shape=(32, 5, 20, 5) dtype=float32>,
 'test_s_h': <tf.Tensor 'shuffle_batch:13' shape=(32, 5, 20, 8, 8, 16) dtype=float32>}
Traceback (most recent call last):
  File "trainer.py", line 344, in <module>
    main()
  File "trainer.py", line 341, in main
    trainer.train()
  File "trainer.py", line 164, in train
    self.batch_train, step=s, is_train=True)
  File "trainer.py", line 199, in run_single_step
    fetch_values = self.session.run(fetch, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 51 is not in [0, 51)
	 [[Node: Program_Decoder/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Program_Decoder/Token_Embedding/embedding_map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Program_Decoder/Token_Embedding/embedding_map/read, Program_Decoder/concat)]]

Caused by op u'Program_Decoder/embedding_lookup', defined at:
  File "trainer.py", line 344, in <module>
    main()
  File "trainer.py", line 337, in main
    trainer = Trainer(config, dataset_train, dataset_test)
  File "trainer.py", line 80, in __init__
    global_step=self.global_step)
  File "/home/disele/Documents/PROJ_program_synth/demo2program/models/baselines/model_synthesis.py", line 187, in __init__
    self.build(is_train=is_train)
  File "/home/disele/Documents/PROJ_program_synth/demo2program/models/baselines/model_synthesis.py", line 475, in build
    embedding_dim=embedding_dim, scope='Program_Decoder', reuse=False
  File "/home/disele/Documents/PROJ_program_synth/demo2program/models/baselines/model_synthesis.py", line 417, in LSTM_Decoder
    unroll_type=unroll_type)
  File "/home/disele/Documents/PROJ_program_synth/demo2program/models/baselines/model_synthesis.py", line 365, in get_DecoderHelper
    embedding = embedding_lookup(gt_tokens)
  File "/home/disele/Documents/PROJ_program_synth/demo2program/models/baselines/model_synthesis.py", line 280, in embedding_lookup
    embedding = tf.nn.embedding_lookup(embedding_map, t)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 294, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 123, in _embedding_lookup_and_transform
    result = _gather_and_clip(params[0], ids, max_norm, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 57, in _gather_and_clip
    embs = array_ops.gather(params, ids, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2409, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1219, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[0,0] = 51 is not in [0, 51)
	 [[Node: Program_Decoder/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Program_Decoder/Token_Embedding/embedding_map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Program_Decoder/Token_Embedding/embedding_map/read, Program_Decoder/concat)]]

2018-09-12 15:19:03.408287: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
2018-09-12 15:19:03.408381: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'float32'
Exception in thread Thread-8 (most likely raised during interpreter shutdown):2018-09-12 15:19:03.408733: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
Exception in thread Thread-25 (most likely raised during interpreter shutdown):Exception in thread Thread-31 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
2018-09-12 15:19:03.409015: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 754, in run
 Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 754, in run  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run2018-09-12 15:19:03.409400: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run2018-09-12 15:19:03.409550: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'zeros'
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable2018-09-12 15:19:03.409657: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
Exception in thread Thread-32 (most likely raised during interpreter shutdown):
2018-09-12 15:19:03.409740: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__Exception in thread Thread-12 (most likely raised during interpreter shutdown):Exception in thread Thread-9 (most likely raised during interpreter shutdown):

 
<type 'exceptions.TypeError'>: 'NoneType' object is not callableException in thread Thread-36 (most likely raised during interpreter shutdown):

Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
Exception in thread Thread-24 (most likely raised during interpreter shutdown):Traceback (most recent call last):

2018-09-12 15:19:03.410391: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'PY3'
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

   File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner2018-09-12 15:19:03.410502: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

 Exception in thread Thread-7 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 754, in run2018-09-12 15:19:03.410732: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/threading.py", line 754, in runTraceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerTraceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 754, in run

2018-09-12 15:19:03.410855: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _runException in thread Thread-16 (most likely raised during interpreter shutdown):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _runException in thread Thread-19 (most likely raised during interpreter shutdown):
Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _runException in thread Thread-27 (most likely raised during interpreter shutdown):

  File "/usr/lib/python2.7/threading.py", line 754, in run

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerTraceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/threading.py", line 754, in run  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
2018-09-12 15:19:03.411391: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__2018-09-12 15:19:03.411567: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__

<type 'exceptions.TypeError'>: 'NoneType' object is not callable
 Exception in thread Thread-11 (most likely raised during interpreter shutdown):  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__<type 'exceptions.TypeError'>: 'NoneType' object is not callable
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Traceback (most recent call last):

<type 'exceptions.TypeError'>: 'NoneType' object is not callable  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner<type 'exceptions.TypeError'>: 'NoneType' object is not callable
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/threading.py", line 754, in run2018-09-12 15:19:03.412149: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
Exception in thread Thread-20 (most likely raised during interpreter shutdown):

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
 
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
2018-09-12 15:19:03.416161: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
Traceback (most recent call last):Exception in thread Thread-37 (most likely raised during interpreter shutdown):
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
2018-09-12 15:19:03.416298: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

 Exception in thread Thread-30 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner2018-09-12 15:19:03.416570: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'PY3'
Exception in thread Thread-18 (most likely raised during interpreter shutdown):
 Exception in thread Thread-6 (most likely raised during interpreter shutdown):2018-09-12 15:19:03.416805: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

Traceback (most recent call last):
Traceback (most recent call last):Traceback (most recent call last):
2018-09-12 15:19:03.416944: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'PY3'
  File "/usr/lib/python2.7/threading.py", line 754, in run
Traceback (most recent call last):
 Exception in thread Thread-39 (most likely raised during interpreter shutdown):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner2018-09-12 15:19:03.417171: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
 
  File "/usr/lib/python2.7/threading.py", line 754, in run
2018-09-12 15:19:03.417330: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerException in thread Thread-15 (most likely raised during interpreter shutdown):
Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner2018-09-12 15:19:03.417508: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

 Exception in thread Thread-2 (most likely raised during interpreter shutdown):  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run

 Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run2018-09-12 15:19:03.417695: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__Exception in thread Thread-17 (most likely raised during interpreter shutdown):Exception in thread Thread-14 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
 Exception in thread Thread-26 (most likely raised during interpreter shutdown): 
Traceback (most recent call last):
Traceback (most recent call last):

Traceback (most recent call last):
Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run  File "/usr/lib/python2.7/threading.py", line 754, in run

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

Exception in thread Thread-35 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__

<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 495, in run
 

<type 'exceptions.TypeError'>: 'NoneType' object is not callable  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/contextlib.py", line 50, in __exit__  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/threading.py", line 754, in run<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 754, in runTraceback (most recent call last):
2018-09-12 15:19:03.419052: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-10 (most likely raised during interpreter shutdown):
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner2018-09-12 15:19:03.419395: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__

<type 'exceptions.TypeError'>: 'NoneType' object is not callableException in thread Thread-38 (most likely raised during interpreter shutdown):Traceback (most recent call last):
2018-09-12 15:19:03.419725: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

  File "/usr/lib/python2.7/threading.py", line 754, in run

Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run2018-09-12 15:19:03.419871: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

 

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
2018-09-12 15:19:03.420069: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__Exception in thread Thread-29 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Exception in thread Thread-13 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 754, in run

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerException in thread Thread-34 (most likely raised during interpreter shutdown):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/threading.py", line 754, in run2018-09-12 15:19:03.420351: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'
  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 754, in run  File "/usr/lib/python2.7/weakref.py", line 330, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Traceback (most recent call last):2018-09-12 15:19:03.420482: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

Traceback (most recent call last):2018-09-12 15:19:03.420560: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'Reference'

   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 264, in _run
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

**Comment by XgDuan** [comment]
https://github.com/shaohua0116/demo2program/issues?q=is%3Aissue+is%3Aclosed
